# Generated by Django 2.2 on 2023-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20231201_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
